name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            echo "Masuk ke server EC2"
            cd /home/ec2-user/UTS_awan

            echo "Pull update dari GitHub"
            git pull origin main

            echo "Install dependencies"
            npm install

            echo "Set environment variables"
            export AWS_REGION=${{ secrets.AWS_REGION }}
            export S3_BUCKET_NAME=${{ secrets.S3_BUCKET_NAME }}
            export AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}
            export AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}

            echo "Restart aplikasi pakai PM2"
            pm2 reload UTS_awan || pm2 start index.js --name UTS_awan
